# Generated by Django 4.1.5 on 2023-02-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
