# Generated by Django 4.1.5 on 2023-02-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartnumber', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=3)),
                ('balance', models.FloatField(default=0)),
                ('expiry', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'PaymentMaster',
            },
        ),
    ]
