# Generated by Django 4.1.5 on 2023-02-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_paymentmaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmaster',
            old_name='cartnumber',
            new_name='cardnumber',
        ),
    ]
