# Generated by Django 4.1.5 on 2023-03-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_rename_cartnumber_paymentmaster_cardnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price1',
            field=models.FloatField(default=200),
        ),
        migrations.AlterField(
            model_name='paymentmaster',
            name='balance',
            field=models.FloatField(default=1000),
        ),
    ]
