# Generated by Django 4.1.5 on 2023-03-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_product_price1_alter_paymentmaster_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price1',
        ),
    ]
